### ISSUE TITLE
getting json decoder error (just downloaded at 3/22/2019 07:55 CST)

### ISSUE THREAD

**Issue by xxKeith20xx** [wustho/epr#3]
~/epr.py myfile.epub (happens with epr.py --help too)

Traceback (most recent call last):
  File "/home/user/epr.py", line 44, in <module>
    state = json.load(f)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

**Comment by wustho** [comment]
Is this happens for every epub file you own?
Can I know the file name of that epub file?

**Comment by wustho** [comment]
Does it help deleting config file `$HOME/.epr`? sorry, every last reading you made will be lost. I made change for state saving format from INI to JSON... since INI couldnt handle filenames with `[` or `]` in it...

**Comment by xxKeith20xx** [comment]
Ah, that was it! Thanks!
