### ISSUE TITLE
Failed to open epub file

### ISSUE THREAD

**Issue by sutrisnob45** [wustho/epr#40]
sometimes got this error when opening my ebook,

> Traceback (most recent call last):
  File "epr.py", line 1240, in <module>
  File "epr.py", line 1236, in main
  File "curses\__init__.py", line 102, in wrapper
  File "epr.py", line 1122, in preread
  File "epr.py", line 194, in initialize
ValueError: '../Text/cover.xhtml' is not in list
[4060] Failed to execute script epr

**Comment by wustho** [comment]
Hello there, sorry about that, but can you send the link to that problematic epub? Since I haven't encountered any such problem...
