### ISSUE TITLE
Termux related problem while opening epr

### ISSUE THREAD

**Issue by tathastu871** [wustho/epr#44]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/epr", line 8, in <module>                                                                   sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/epr.py", line 1253, in main
    curses.wrapper(preread, file)
  File "/data/data/com.termux/files/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/epr.py", line 1143, in preread
    epub.initialize()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/epr.py", line 198, in initialize
    name = j.find("DAISY:navLabel/DAISY:text", self.NS).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by wustho** [comment]
Hello there, seems like issue with the epub. Some epubs was just not structured according standard... Maybe you can try other epub file for the same book title? Or opening the epub with epr fork: https://github.com/wustho/epy it will give detailed error if book is not well structured.

**Comment by tathastu871** [comment]
with epy it opens properly

**Comment by tathastu871** [comment]
another epub opened properly with epr but some epub doesn't but same epub opened properly with epy

**Comment by wustho** [comment]
Ah thanks for detailed traceback will check it out...
