### ISSUE TITLE
[Win 11] Can't open images

### ISSUE THREAD

**Issue by RitschAlex** [wustho/epr#60]
I can't open images.

![image](https://user-images.githubusercontent.com/70853152/216338936-3c8cf8f9-de9b-457b-996e-2aed60e82331.png)

**Comment by hnvy** [comment]
Getting the same error on `epr24.exe` (but not `epr23.exe`). See the error below:

The issue seems to be fixed in [epy](https://github.com/wustho/epy).

```
Traceback (most recent call last):
  File "epr.py", line 1272, in <module>
  File "epr.py", line 1268, in main
  File "curses\__init__.py", line 94, in wrapper
  File "epr.py", line 1162, in preread
  File "epr.py", line 1055, in reader
  File "epr.py", line 648, in open_media
  File "subprocess.py", line 345, in call
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[12104] Failed to execute script 'epr' due to unhandled exception!
```

**Comment by kai0200** [comment]
You can try

1036 # img = re.search("(?<=[IMG:)[0-9]+(?=])", i)
img = re.search("[IMG:[0-9]+]", i)

1044 #impath = imgs[int(gambar[0])
impath = imgs[int(gambar[0].strip('[]').split(':')[1])]
